#! /bin/sh
#
# /init executable file in the initramfs
#
# mounts /dev /proc /sys, sets up `lo` and starts a shell on /dev/console
# when the shell exits, the VM is stopped
#

trap 'exit 1' INT HUP QUIT TERM ALRM USR1
trap 'poweroff' EXIT

### Firecracker does not exit the host program on `poweroff`, just on reboot.
### Cloud-hypervisor is the opposite (on reboot, it does a soft-restart of the guest)
poweroff() {
    if grep -q cloud-hypervisor /sys/firmware/dmi/entries/0-0/raw; then
      poweroff -f
    else
      reboot -f
    fi
}

mount -t devtmpfs dev /dev

### Early exit - used to test how fast a VM gets to this point
if [ -n "$TEST_STRING" ]; then
    echo $TEST_STRING > /dev/console
    exit
fi

mount -t proc proc /proc
mount -t sysfs sysfs /sys

ip link set up dev lo

# mount -t virtiofs myfs /mnt

/sbin/getty -n -l /bin/sh 115200 /dev/console
